### PR TITLE
Add first set of WayWise usage examples

### PR DESCRIPTION
**Pull request by marvind**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Rather doc update than feature. It is part of the quest to make WayWise more accessible to others.
The examples folder adds three usage examples:
    - RCCar_MAVLINK_autopilot: was previously a separate repository "RCCar_minimal_example", moving it here makes WayWise more self-contained
    - RCCar_ISO22133_autopilot: same as previous example but using ISO 22133 based communication contributed by AstaZero instead of MAVLINK. @Robert108 could you test this one towards ATOS?
    - map_local_twocars: simple ui example showing two cars driving in circles on a map

* **What is the current behavior?** (You can also link to an open issue here)
No examples.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No. Added very minor stability fixes while creating the examples but no functionality is changed.

Will add more UI examples whenever I find time... 🙂

### CODE REVIEW

**Review by ariamirzai — COMMENTED** [review]
- map_local_twocars: Works well, I'd only ask it to be clarified in the readme that building instructions need to be executed inside each respective example folder.
- RCCar_MAVLINK_autopilot: Runs but I'm not getting a UI-window? Have tried to run together with ControlTower as well without success.
- RCCar_ISO22133_autopilot: Will not build, assuming ATOS is required?

**Comment by Robert108** [comment]
@marvind I have tested this towards ATOS and it runs and connects as expected. @ariamirzai Were all the isoObject submodules fetched? The isoObject it self contains other submodule so you will need to run git submodule update **--init --recursive**. 
I found one problem though. The iso22133 vehicleserver assumes a ubloxrover has been set when receiving an OSEM message from ATOS. In the examples in which there is no ublox component this makes the app seg fault. A null check could prevent this and lead to a better error message. I'll add this in another PR!

**Comment by marvind** [comment]
>     * RCCar_MAVLINK_autopilot: Runs but I'm not getting a UI-window? Have tried to run together with ControlTower as well without success.

Fixed this. The latest commit on main assumes that you set an ID on your vehicle (other than 0), which I missed. It should connect to ControlTower just fine now.

**Comment by marvind** [comment]
> @marvind I have tested this towards ATOS and it runs and connects as expected. @ariamirzai Were all the isoObject submodules fetched? The isoObject it self contains other submodule so you will need to run git submodule update **--init --recursive**. I found one problem though. The iso22133 vehicleserver assumes a ubloxrover has been set when receiving an OSEM message from ATOS. In this examples in which there is no ublox component this makes the app seg fault. A null check could prevent this and lead to a better error message. I'll add this in another PR!

Perfect, thank you!

Thanks for testing, everyone.

**Review by ariamirzai — APPROVED** [review]
Thanks for the fix, RCCar_MAVLINK_autopilot works now.

**Pull request merged**
